### ISSUE TITLE
Feature Request - Krunner trufflehog capability to report only verified secrets

### ISSUE THREAD

**Issue by kai-berberich** [kospex/kospex#10]
It would be great to be able to add CL argument for verified secrets reporting only in Trufflehog scans - for added accuracy.
This would require capability to toggle --only-verified  flag in the commandline.
Happy to discuss further
cheers
Kai

**Comment by sabbaticas** [comment]
Thanks for the feature request, I will aim to get out in a new release to PyPi over the next week.

**Comment by sabbaticas** [comment]
Feature now deployed in v0.0.10 to PyPi
